window.COCODERAS_MESSAGES = [
    "Este coco venía con una misión: recordarte que eres una personita MUYYYYY especial",
    "NUNCA le ruegues a nadie bro, porque eres una personita que no merece migajas🐦",
    "Remember, somebody made this for you porque te quiere<3",
    "Que nunca te falten razones pequeñas como tú, para sentirte querida<3",
    "Este coco no trae agüita, trae una notita para decirte que te quiere muchísimo",
    "Este coco se durmió, abre otro para obtener otro mensajito 💕",
    "Siempre habrá alguien que se preocupe por ti, solo que recuerda que a veces da penita estar recordandolo",
    "¿¿SABÍAS QUE TIENES UNA SONRISA HERMOSISISISISIMA??",
    "Cuando te sientas mal, arregla la silla y te sientas mejor",
    "Podré no ser tu mejor amigo, pero sabes que siempre estaré ahí para cuando lo necesites<3",
    "COCO-DERASSSSSSSSSSSSSSSSSSS",
    "Te cuento un secreto, tu cabello se me hace muy bonito KJSKJAKJSAJKS",
    "QUIERES QUE TE DIGA ALGO??? Algo🗣️‼️🔥",
    "Lo estás haciendo muy bien, plisito, jamás te rindas",
    "¿¿Te sientes cansadita?? Quizás podría ser un gran momento para descansar un poco",
    "¿Qué le dijo un techo a otro techo? Techo-de menos SJAKSKJAKJSAKJS",
    "Este coco chambeó todo el día, déjalo dormir we",
    "El camino a veces puede ser complicado, PEEERO YO SÉ QUE TU PUEDESSS, ÁNIMO",
    "Nunca olvides, la hipotenusa es: C al cuadrado = A al cuadrado + B al cuadrado",
    "67",
    "No es por nada, pero, WHY ARE U SO PRETTY??",
    "NO OLVIDES TOMAR AGUAAAAA",
    "AL IGUAL QUE LOS COCOS, TU TMN NECESITAS AGUA, TOMA AGUAAAAA",
    "¿¿Sabías que la miel NUNCA caduca??",
    "Has conseguido +1000 de aura con este coco bro",
    "JAMÁS Te olvides de sonreír",
    "El mundo necesita más personas como tú<3",
    "YO SÉ QUE TU PUEDESSSSS",
    "Respira, todo estará bien",
    "Recuerda, TODO empieza con un pequeño paso",
    "Te deseo mucha suerte",
    "Este coco se siente muy orgulloso de ti🥥",
    "No todos los cocos son iguales...",
    "No sé, pregúntale a Chatgepete",
    "Recuerda, nunca es tarde para empezar",
    "¿¿Sabías que... los tiburones existían antes que los mismisimos árboles??",
    "¿¿Sabías que... el bambú puede crecer casi un metro cada día??",
    "A veces perderse también es avanzar",
    "Las raíces también crecen en silencio",
    "Que tu cansancio nunca impida que seas feliz<3",
    "Incluso la antorcha más pequeña, puede iluminar la cueva más grande",
    "Agradece a Dios por un día más de vida",
    "No olvides agradecer, por un día más para poder intentarlo",
    "Ntps, llorar está bien",
    "Cada amanecer trae una nueva oportunidad para construir",
    "No dejes que el miedo te venza, tu puedes con eso y más",
    "Recuerda bro, descansar también es importante",
    "Puedes caer six veces... pero levántate seven",
    "Recuerda, la vida es un juego de sube y baja",
    "Don't worry, be happy",
    "Anda, ve a ver ese K-Drama que tienes pendiente",
    "La vida está tan complicada que ya no puedes ver K-Dramas como antes🥀",
    "A la gente ya no se le caen los billetes como antes🥀",
    "Ya te dije que te quiero? Pues te quiero we",
    "Este coco no tiene ojos, pero aún así alcanza a ver lo hermosa que eres",
    "Recuerda hacer tus rachas (si aún tienes🔥)",
    "ANDAAAA, NO TE RINDASSSS",
    "Me pregunto si algún día leerás TOOODAS estas notitas",
    "El corazón es como la bedrock, solo se destruye con engaños🥀",
    "No destruyas tu mundo por un mal momento...",
    "Cuando mueres, empiezas desde 0, pero con una experiencia más...",
    "Si we, hay algunas frases de Minecraft por ahí KSJAKJSKJAKJSJK",
    "No esperes encontrar diamantes en una cueva donde ya colocaron antorchas...",
    "Te quiero 3000",
    "Los árboles más altos también fueron semillas pequeñas",
    "Este coco no sabe hablar, pero igual quería decirte que eres increíble<3",
    "No todos los días tienen diamantes, pero todos tienen algo que encontrar",
    "Quizás no encontraste este coco, quizás él te encontró a ti...",
    "Tu dedo tiene Fortuna III para abrir cocos",
    "El coco dijo que te ves bien hoy, saber cómo sabe eso...",
    "Tu vida podrá tener bugs, pero también puedes corregirlos",
    "No eres un código roto, solo estás en proceso de mejora",
    "Tu vida tiene más líneas de código de las que imaginas",
    "Si algún día dudas de ti, la verdad es que te falla bro",
    "ANDAAA, HAZLO POR SUGAAAA",
    "SWIM SWIM🏊",
    "IF YOU WANNA BE ANIMALS, BABY WE CAN BE ANIMALS🗣️‼️🎶",
    "Si tu quieres bailar, sopa de caracol🗣️‼️",
    "TOMA AGUA DERASSSSSSSS",
    "Tu puedes, fuerzas leona",
    "Nataly, si tienes hambre, come",
    "Con mucho cariño, de mi, para tu",
    "Si llegas a tener problemas de autoestima, que sepas que te falla bro",
    "Cuida tus rodillas, no tenemos de repuesto",
    "Nunca dudes de tus capacidades, tu eres capaz de todo",
    "Suga estaría orgulloso de ti",
    "Eres hermosa, como un gran ramo de tulipanes🌷",
    "When life gives you tangerines",
    "Nunca es tarde para empezar de nuevo",
    "La Meli dice que te quiere muchote",
    "Eres una persona muy linda, lo sabías?",
    "Eres una persona digna de admirar",
    "Eres una personita muy increíble bro",
    "Deberías considerar cerrar el papoi🤫",
    "Nunca te rindas, tucan tucan",
    "Salchichona",
    "Anda a dormirte",
    "Shut up bro",
    "¿Te diste cuenta que las fases de la luna van cambiando?",
    "Actually, este es el mensaje número 100 SKAKSJJAKSJK",
    "No eres un NPC, eres la protagonista de tu propia historia",
    "No te apresures, sigue tu propio ritmo we",
    "Este coco no tiene GPS, pero aún así encontró el camino hacia ti",
    "Tu sonrisa tiene más brillo que una armadura encantada💎",
    "Este coco te da +50 de energía para que sigas adelante",
    "Hasta la luna tiene fases, tu también puedes cambiar",
    "Tu alma tiene más brillo que un beacon al máximo",
    "Los mejores mundos también se construyen bloque por bloque",
    "Si la vida te manda zombis, planta girasoles y sigue adelante🌻",
    "Crazy Dave vendió su último taco para comprar un girasol... y aun así dice que tú vales más",
    
];